[env:nucleo_f031k6]
platform = ststm32
board = nucleo_f031k6
framework = cmsis

build_flags = 
    -Wl,-Map=output.map
    -Wl,--cref

    -Os
    -flto
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections